### ISSUE TITLE
System.NullReferenceException: 'Object reference not set to an instance of an object.'

### ISSUE THREAD

**Issue by GetTeched** [GetTeched/CodeReviews.Console.Calculator#15]
No idea how this happened

**Comment by CloudeaSoft** [comment]
Please describe your issue with more detail, such as it crashed in which file, in which line and by which variable.

**Comment by GetTeched** [comment]
Sorry, this happened on CalculatorLibrary.cs line 127, I just put this here to try reproduce this error because I could not reproduce it after I completed a previous issue #14 so it might have been linked, so think this has been resolved.
